config/routes.rb
Rails.application.routes.draw do
  
  resources :flash_cards
  resources :user_echanges, except: [:create, :new]
  resources :flashes, except: [:create, :index, :new]
  
  
  #Course items
  resources :courses, shallow: true do
    resources :flashes, only: [:create, :index, :new]
    resources :user_echanges, only: [:create, :new]
  end
  #resources :flash_cards, except:[:index, :show] do
    # resources :line_items, except: [:index, :show]
  #end
  
  #Membership
  get "teacher-sign-up" , to:'membership#teacherUp'
  get "teacher-sign-in" , to:'membership#teacherIn'
  get "ambassadeur-sign-up" , to:'membership#ambassadorUp'
  get "ambassadeur-sign-in" , to:'membership#ambassadorIn'
  get "team-sign-up" , to:'membership#teamUp'
  get "team-sign-in" , to:'membership#teamIn'

   #Home && Feed
  get "home", to:'home#index'

  #Courses
  get "courses-show", to:"courses#show"
  get "feed", to:"courses#index"
  get "lesson", to:"courses#new"
  
  #Dashboard
  get "dashboard", to:'dashboard#index'
  get "setting", to:'dashboard#home'
  get "new-materials", to:"materials#new"
  get "new-levels", to:"levels#new"
  get "new-city", to:"citytowns#new"
  get "new-school", to:"schools#new"

  
  resources :courses
  resources :user_roles
  resources :schools
  resources :citytowns
  resources :materials
  resources :levels
  
  #Membership 
  devise_scope :user do
    get '/student-sign-in', to: 'devise/sessions#new'
    get '/student-sign-up', to: 'devise/registrations#new', as: "new_user_registration"
    delete '/sign-out', to: 'devise/sessions#destroy'
  end

  devise_for :users
  root to:'homepage#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user_echange.rb
class UserEchange < ApplicationRecord
  belongs_to :course
  belongs_to :user
  has_rich_text :content
  has_rich_text :wiki


 ################## FIX N+1  ###############
Course.all.with_rich_text_content # Preload the body without attachments.
Course.all.with_rich_text_content_and_embeds # Preload both body and attachments.


##### STATUS  ########
STATUS = ["Lune", "Old"]

  ################## SLUG ###############
  validates :title, :course_id, :user_id, :slug, presence: true

  def slugged_custom
    #Apprendre-a-calculer-les-limites-math-tleD
    "#{title} #{course_id}"
  end

  extend FriendlyId
    friendly_id :slugged_custom, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end

end

app/controllers/user_echanges_controller.rb
class UserEchangesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_course, only: %i[create, new]
  before_action :set_user_echange, only: %i[ show edit update destroy ]

  # GET /user_echanges or /user_echanges.json
  def index
    @user_echanges = UserEchange.all
  end

  # GET /user_echanges/1 or /user_echanges/1.json
  def show
    
  end

  # GET /user_echanges/new
  def new
    @user_echange = @course.user_echanges.build
  end

  # GET /user_echanges/1/edit
  def edit
  end

  # POST /user_echanges or /user_echanges.json
  def create
    @user_echange = @course.user_echanges.build(user_echange_params)
    @user_echange.user_id = current_user.id 
    
    respond_to do |format|
      if @user_echange.save
        format.html { redirect_to feed_path, notice: "User echange was successfully created." }
        format.json { render :show, status: :created, location: @user_echange }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_echange.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_echanges/1 or /user_echanges/1.json
  def update
    respond_to do |format|
      if @user_echange.update(user_echange_params)
        format.html { redirect_to user_echange_url(@user_echange), notice: "User echange was successfully updated." }
        format.json { render :show, status: :ok, location: @user_echange }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_echange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_echanges/1 or /user_echanges/1.json
  def destroy
    @user_echange.destroy

    respond_to do |format|
      format.html { redirect_to user_echanges_url, notice: "User echange was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_echange
      @user_echange = UserEchange.friendly.find(params[:id])
    end

     #Find course
    def set_course
      @course = Course.friendly.find(params[:course_id])
    end

    # Only allow a list of trusted parameters through.
    def user_echange_params
      params.require(:user_echange).permit(:title, :content, :wiki, :status, :slug, :course_id, :user_id)
    end
end

app/helpers/user_echanges_helper.rb
module UserEchangesHelper
end

app/views/user_echanges/_form.html.erb
<%= form_with(model: @user_echange, url: [@course, user_echange], class: "contents") do |f| %>
  <% if user_echange.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user_echange.errors.count, "error") %> prohibited this user_echange from being saved:</h2>

      <ul>
        <% user_echange.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= f.text_field :title, placeholder:"Posez votre question avec comment ...", class: "ln-field rounded-md" %>
  </div>

  

  

  <div class="inline">
    <%= f.submit "Envoi", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/user_echanges/_user_echange.html.erb
<div class="border" id="<%= dom_id user_echange %>">
  
<!-- component -->
<div class="flex h-screen antialiased text-gray-800">
    <div class="flex flex-row h-full w-full overflow-x-hidden">
      
      <div class="flex flex-col flex-auto h-full p-6">
      <p class="text-white font-semibold"> <%= user_echange.title %></p>
        <div class="flex flex-col flex-auto flex-shrink-0 rounded-2xl bg-gray-100 h-full p-4">
          <div class="flex flex-col h-full overflow-x-auto mb-4">
            <div class="flex flex-col h-full">
              <div class="grid grid-cols-12 gap-y-2">
                <!-- Question-->
                <div class="col-start-1 col-end-8 p-3 rounded-lg">
                  <div class="flex flex-row items-center">
                    
                    <div class="relative ml-3 text-sm bg-white p-2 rounded-md" >
                      <div>
                        <div class="border border-b-2">Kama Kara - Eleve</div>
                      <div class="max-w-md" >Hey How are you today? ey How are you today?ey How are you today?ey How are you today?</div>
                      </div>
                    </div>
                  </div>
                </div>
                
                <!-- Anwser-->
                <div class="col-start-6 col-end-13 p-3 rounded-lg">
                  <div class="flex items-center justify-start flex-row-reverse">
                    
                    <div class="relative mr-3 text-sm bg-indigo-100 p-2 rounded-md">
                      <div>
                        <div class="border border-b-2">Kama Kara - Eleve</div>
                      <div class="max-w-md" >Hey How are you today? ey How are you today?ey How are you today?ey How are you today?</div>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Question-->
                <div class="col-start-1 col-end-8 p-3 rounded-lg">
                  <div class="flex flex-row items-center">
                    
                    <div class="relative ml-3 text-sm bg-white p-2 rounded-md" >
                      <div>
                        <div class="border border-b-2">Kama Kara - Eleve</div>
                      <div class="max-w-md" >Hey How are you today? ey How are you today?ey How are you today?ey How are you today?</div>
                      </div>
                    </div>
                  </div>
                </div>
                
                <!-- Anwser-->
                <div class="col-start-6 col-end-13 p-3 rounded-lg">
                  <div class="flex items-center justify-start flex-row-reverse">
                    
                    <div class="relative mr-3 text-sm bg-indigo-100 p-2 rounded-md">
                      <div>
                        <div class="border border-b-2">Kama Kara - Eleve</div>
                      <div class="max-w-md" >Hey How are you today? ey How are you today?ey How are you today?ey How are you today?</div>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Question-->
                <div class="col-start-1 col-end-8 p-3 rounded-lg">
                  <div class="flex flex-row items-center">
                    
                    <div class="relative ml-3 text-sm bg-white p-2 rounded-md" >
                      <div>
                        <div class="border border-b-2">Kama Kara - Eleve</div>
                      <div class="max-w-md" >Hey How are you today? ey How are you today?ey How are you today?ey How are you today?</div>
                      </div>
                    </div>
                  </div>
                </div>
                
                <!-- Anwser-->
                <div class="col-start-6 col-end-13 p-3 rounded-lg">
                  <div class="flex items-center justify-start flex-row-reverse">
                    
                    <div class="relative mr-3 text-sm bg-indigo-100 p-2 rounded-md">
                      <div>
                        <div class="border border-b-2">Kama Kara - Eleve</div>
                      <div class="max-w-md" >Hey How are you today? ey How are you today?ey How are you today?ey How are you today?</div>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Question-->
                <div class="col-start-1 col-end-8 p-3 rounded-lg">
                  <div class="flex flex-row items-center">
                    
                    <div class="relative ml-3 text-sm bg-white p-2 rounded-md" >
                      <div>
                        <div class="border border-b-2">Kama Kara - Eleve</div>
                      <div class="max-w-md" >Hey How are you today? ey How are you today?ey How are you today?ey How are you today?</div>
                      </div>
                    </div>
                  </div>
                </div>
                
                <!-- Anwser-->
                <div class="col-start-6 col-end-13 p-3 rounded-lg">
                  <div class="flex items-center justify-start flex-row-reverse">
                    
                    <div class="relative mr-3 text-sm bg-indigo-100 p-2 rounded-md">
                      <div>
                        <div class="border border-b-2">Kama Kara - Eleve</div>
                      <div class="max-w-md" >Hey How are you today? ey How are you today?ey How are you today?ey How are you today?</div>
                      </div>
                    </div>
                  </div>
                </div>
                
              </div>
            </div>
          </div>
          <div class="flex flex-row items-center h-16 rounded-xl bg-white w-full px-4">
            
            <div class="flex-grow ml-4">
              <div class="relative w-full">
                <!-- Input-->
                <!-- Input-->
                <input
                  type="text"
                  class="flex w-full border rounded-xl focus:outline-none focus:border-indigo-300 pl-4 h-10" placeholder="votre message" />
                
              </div>
            </div>
            <div class="ml-2">
              <button class="flex items-center justify-center bg-blue-600 hover:bg-indigo-600 rounded-xl text-white px-4 py-1 flex-shrink-0">
               
                <span class="mx-2">
                  <svg
                    class="w-4 h-4 transform rotate-90 hover:rotate-45 -mt-px"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"
                    ></path>
                  </svg>
                </span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/user_echanges/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user echange</h1>

  <%= render "form", user_echange: @user_echange %>

  <%= link_to "Show this user echange", @user_echange, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to user echanges", user_echanges_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/user_echanges/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">User echanges</h1>
    <%= link_to 'New user echange', root_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="user_echanges" class="min-w-full">
    <%= render @user_echanges %>
  </div>
</div>

app/views/user_echanges/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user echange</h1>

  <%= render "form", user_echange: @user_echange %>

  <%#= link_to 'Back to user echanges', user_echanges_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/user_echanges/show.html.erb
<% @title="Echange" %>
<div class="max-h-screen bg-black w-full flex">
	<div class="mx-auto">
		<%= render @user_echange %>
	</div>
</div>