config/routes.rb
Rails.application.routes.draw do
  
  resources :flash_cards
  resources :user_echanges, except: [:create, :new]
  resources :flashes, except: [:create, :index, :new]
  
  
  #Course items
  resources :courses, shallow: true do
    resources :flashes, only: [:create, :index, :new]
    resources :user_echanges, only: [:create, :new]
  end
  #resources :flash_cards, except:[:index, :show] do
    # resources :line_items, except: [:index, :show]
  #end
  
  #Membership
  get "teacher-sign-up" , to:'membership#teacherUp'
  get "teacher-sign-in" , to:'membership#teacherIn'
  get "ambassadeur-sign-up" , to:'membership#ambassadorUp'
  get "ambassadeur-sign-in" , to:'membership#ambassadorIn'
  get "team-sign-up" , to:'membership#teamUp'
  get "team-sign-in" , to:'membership#teamIn'

   #Home && Feed
  get "home", to:'home#index'

  #Courses
  get "courses-show", to:"courses#show"
  get "feed", to:"courses#index"
  get "lesson", to:"courses#new"
  
  #Dashboard
  get "dashboard", to:'dashboard#index'
  get "setting", to:'dashboard#home'
  get "new-materials", to:"materials#new"
  get "new-levels", to:"levels#new"
  get "new-city", to:"citytowns#new"
  get "new-school", to:"schools#new"

  
  resources :courses
  resources :user_roles
  resources :schools
  resources :citytowns
  resources :materials
  resources :levels
  
  #Membership 
  devise_scope :user do
    get '/student-sign-in', to: 'devise/sessions#new'
    get '/student-sign-up', to: 'devise/registrations#new', as: "new_user_registration"
    delete '/sign-out', to: 'devise/sessions#destroy'
  end

  devise_for :users
  root to:'homepage#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/flash.rb
class Flash < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_rich_text :content
  
  #setup validation and uniqueness
  validates :title, presence: true, uniqueness: { scope: :course_id }
  validates :content, :slug, :user_id, :course_id, presence: true

  #Slugged concern
  include ItemsSlugged


end

app/controllers/flashes_controller.rb
class FlashesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course
  before_action :set_flash, only: %i[ show edit update destroy ]

  # GET /flashes or /flashes.json
  def index
    @flashes = Flash.all
  end

  # GET /flashes/1 or /flashes/1.json
  def show
  end

  # GET /flashes/new
  def new
    @flash = @course.flashes.build
  end

  # GET /flashes/1/edit
  def edit
  end

  # POST /flashes or /flashes.json
  def create
    @flash = @course.flashes.build(flash_params)
    @flash.user_id = current_user.id
    respond_to do |format|
      if @flash.save
        format.html { redirect_to feed_path, notice: "Flash was successfully created." }
        format.json { render :show, status: :created, location: @flash }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flashes/1 or /flashes/1.json
  def update
    respond_to do |format|
      if @flash.update(flash_params)
        format.html { redirect_to flash_url(@flash), notice: "Flash was successfully updated." }
        format.json { render :show, status: :ok, location: @flash }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flashes/1 or /flashes/1.json
  def destroy
    @flash.destroy

    respond_to do |format|
      format.html { redirect_to flashes_url, notice: "Flash was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flash
      @flash = course.flashes.friendly.find(params[:id])
    end

    #Find course
    def set_course
      @course = Course.friendly.find(params[:course_id])
    end

    # Only allow a list of trusted parameters through.
    def flash_params
      params.require(:flash).permit(:title, :content, :slug, :user_id, :course_id)
    end
end

app/helpers/flashes_helper.rb
module FlashesHelper
end

app/views/flashes/_flash.html.erb
<div id="<%= dom_id flash %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= flash.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= flash.content %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Slug:</strong>
    <%= flash.slug %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= flash.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Course:</strong>
    <%= flash.course_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this flash", flash, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this flash', edit_flash_path(flash), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/flashes/_form.html.erb
<%= form_with(model: @flash, url: [@course, flash], class: "contents") do |f| %>
  <% if flash.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(flash.errors.count, "error") %> prohibited this flash from being saved:</h2>

      <ul>
        <% flash.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= f.text_field :title, placeholder:"Titre du flash ...", class: "ln-field rounded-md" %>
  </div>

  <div class="my-5 bg-white p-2 rounded-md">
    <%= f.label :contenu %>
    <%= f.rich_text_area :content,
     class: "block  rounded-md outline-none px-3 py-2 mt-2 w-full",
    placeholder:"le contenu du flash ..." %>
  </div>

  <div class="inline">
    <%= f.submit "Créer un Flash", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/flashes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing flash</h1>

  <%= render "form", flash: @flash %>

  <%= link_to "Show this flash", @flash, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to flashes", flashes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/flashes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Flashes</h1>
    <%= link_to 'New flash', new_flash_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="flashes" class="min-w-full">
    <%= render @flashes %>
  </div>
</div>

app/views/flashes/new.html.erb
<% @title="Nouveau flash" %>
<div class="mx-auto md:w-2/3 w-full ">
  <h1 class="font-bold text-3xl text-white">Nouveau flash</h1>

  <%= render "form", flash: @flash %>

  <%#= link_to 'Back to flashes', flashes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/flashes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @flash %>

    <%= link_to 'Edit this flash', edit_flash_path(@flash), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this flash', flash_path(@flash), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to flashes', flashes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>