config/routes.rb
Rails.application.routes.draw do
  
  resources :flash_cards
  resources :user_echanges, except: [:create, :new]
  resources :flashes, except: [:create, :index, :new]
  
  
  #Course items
  resources :courses, shallow: true do
    resources :flashes, only: [:create, :index, :new]
    resources :user_echanges, only: [:create, :new]
  end
  #resources :flash_cards, except:[:index, :show] do
    # resources :line_items, except: [:index, :show]
  #end
  
  #Membership
  get "teacher-sign-up" , to:'membership#teacherUp'
  get "teacher-sign-in" , to:'membership#teacherIn'
  get "ambassadeur-sign-up" , to:'membership#ambassadorUp'
  get "ambassadeur-sign-in" , to:'membership#ambassadorIn'
  get "team-sign-up" , to:'membership#teamUp'
  get "team-sign-in" , to:'membership#teamIn'

   #Home && Feed
  get "home", to:'home#index'

  #Courses
  get "courses-show", to:"courses#show"
  get "feed", to:"courses#index"
  get "lesson", to:"courses#new"
  
  #Dashboard
  get "dashboard", to:'dashboard#index'
  get "setting", to:'dashboard#home'
  get "new-materials", to:"materials#new"
  get "new-levels", to:"levels#new"
  get "new-city", to:"citytowns#new"
  get "new-school", to:"schools#new"

  
  resources :courses
  resources :user_roles
  resources :schools
  resources :citytowns
  resources :materials
  resources :levels
  
  #Membership 
  devise_scope :user do
    get '/student-sign-in', to: 'devise/sessions#new'
    get '/student-sign-up', to: 'devise/registrations#new', as: "new_user_registration"
    delete '/sign-out', to: 'devise/sessions#destroy'
  end

  devise_for :users
  root to:'homepage#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/citytown.rb
class Citytown < ApplicationRecord
  belongs_to :user

  #Slugged concern
  include ItemsSlugged

end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  has_many :flashes, dependent: :destroy
  has_many :flash_cards, dependent: :destroy
  has_many :user_echanges, class_name: "UserEchange",
                            foreign_key: "course_id",
                            dependent: :destroy

  ################## FIX N+1  ###############
Course.all.with_rich_text_content # Preload the body without attachments.
Course.all.with_rich_text_content_and_embeds # Preload both body and attachments.


##### STATUS  ########
STATUS = ["Lune", "Old"]

  ################## SLUG ###############
  validates :title, :content, :published,
            :level_name, :material_name,
            :user_id, :slug, :status, presence: true

  def slugged_custom
    #Apprendre-a-calculer-les-limites-math-tleD
    "#{title} #{material_name} #{level_name}"
  end

  extend FriendlyId
    friendly_id :slugged_custom, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end

  #Scopeto find essential for course
  scope :essential, -> { where("feed_course.id = ?", feed_flash.course_id)}
  # Ex:- scope :active, -> {where(:active => true)}
end

app/models/flash.rb
class Flash < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_rich_text :content
  
  #setup validation and uniqueness
  validates :title, presence: true, uniqueness: { scope: :course_id }
  validates :content, :slug, :user_id, :course_id, presence: true

  #Slugged concern
  include ItemsSlugged


end

app/models/flash_card.rb
class FlashCard < ApplicationRecord
  belongs_to :course
  belongs_to :user

  
  #setup validation and uniqueness
  validates :slug, :user_id, :course_id, presence: true
  validates :title, presence: true, uniqueness: { scope: :course_id }
  
  #Slugged concern
  include ItemsSlugged


end

app/models/home.rb
class Home < ApplicationRecord


end   

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :user

  #Slugged concern
  include ItemsSlugged
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :user

  #Slugged concern
  include ItemsSlugged

  
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :user

  #Slugged concern
  include ItemsSlugged

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :trackable,  :authentication_keys => [:logged]

has_many :levels, class_name: "Level", foreign_key: "user_id"
has_many :materials, class_name: "Material", foreign_key: "user_id"
has_many :schools, class_name: "School", foreign_key: "user_id"
has_many :citytowns, class_name: "Citytown", foreign_key: "user_id"
has_many :courses, class_name: "Course", foreign_key: "user_id"
has_many :flashes
has_many :flash_cards
has_many :user_echanges, class_name: "User_echange", foreign_key: "user_id"


            
attr_writer :logged
  #enum :role, student: "student", teacher: "teacher", team: "team", default: "student"
  
  
  ################## VALIDATES  ###############
  before_validation :user_validations?,  on: :create
  before_validation :full_name
   
  
   validates :first_name, :last_name, :full_name, :email, :password,
              :contact, :user_role, :city_name, presence: true

   validates :contact, uniqueness: true, numericality: { only_integer: true }, length: { minimum:10,
              message: "%{ value} verifier votre nom numéro est 10 chiffres"}
              
   validates :user_role, inclusion: { in: %w(Student Teacher Team ambassador),
                    message: "%{value} acces non identifier" }


   ############# CUSTOMIZE ###############""
   
   def user_validations?
    if self.user_role != "Student"
      self.matricule = "#{self.contact}T"
    else 
      self.email = "#{self.matricule}@gmail.com"
      self.password = "#{self.contact}"
    end    
  end

  #FULL_NAME
  def full_name
    self.full_name = "#{self.first_name} #{self.last_name}" 
  end 

################## SLUG ###############
  extend FriendlyId
  friendly_id :user_slugged, use: :slugged
  
  def user_slugged
    [
      :full_name,
    [:full_name, :contact]
    ]
  end
  ################## END SLUGGED #########

  ################## BEFORE SAVE  #########
  before_save do
    self.contact            = contact.strip.squeeze(" ")
    self.first_name         = first_name.strip.squeeze(" ").downcase.capitalize
    self.last_name          = last_name.strip.squeeze(" ").downcase.capitalize
  end
    
  ################## LOGGED  #########
  #permet la connexion avec le matricule
  def logged
    @logged || self.matricule || self.email
  end
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (logged = conditions.delete(:logged))
      where(conditions.to_h).where(["lower(matricule) = :value OR lower(email) = :value", { :value => logged.downcase }]).first
    elsif conditions.has_key?(:matricule) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
  
  ################## End Logged  #########
end

app/models/user_echange.rb
class UserEchange < ApplicationRecord
  belongs_to :course
  belongs_to :user
  has_rich_text :content
  has_rich_text :wiki


 ################## FIX N+1  ###############
Course.all.with_rich_text_content # Preload the body without attachments.
Course.all.with_rich_text_content_and_embeds # Preload both body and attachments.


##### STATUS  ########
STATUS = ["Lune", "Old"]

  ################## SLUG ###############
  validates :title, :course_id, :user_id, :slug, presence: true

  def slugged_custom
    #Apprendre-a-calculer-les-limites-math-tleD
    "#{title} #{course_id}"
  end

  extend FriendlyId
    friendly_id :slugged_custom, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end

end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
   before_action :authenticate_user!
  
  def index
  end

  def home
    @LevelList = Level.all_ordered
    @CityList = Citytown.all_ordered
    @MaterialList = Material.all_ordered
    @SchoolList = School.all_ordered
  end
end

app/helpers/citytowns_helper.rb
module CitytownsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/membership_helper.rb
module MembershipHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/dashboard/home.html.erb
<% @title="Parametres" %>
<!-- component -->
<div class="">
    <div x-data="{ sidebarOpen: false }" class="flex h-screen bg-gray-200">
        <div :class="sidebarOpen ? 'block' : 'hidden'" @click="sidebarOpen = false" class="fixed z-20 inset-0 bg-black opacity-50 transition-opacity lg:hidden"></div>
        <!-- Sidebar -->
        <%= render "dashboard/shared/sidebar" %>
          
        <div class="flex-1 flex flex-col overflow-hidden">
        <!-- Header -->
        <%= render "dashboard/shared/header" %>
            <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
                <div class="container mx-auto px-6 py-8">
                    <h3 class="text-gray-700 text-2xl font-medium">Config Lnclass</h3>
                    <div class="flex flex-col mt-8">
                        <%= render "dashboard/shared/items" %>
                    </div>
                </div>
            </main>
        </div>
    </div>
</div>

app/views/dashboard/index.html.erb
<% @title="Dashboard" %>
<!-- component -->
<div class="">
    <div x-data="{ sidebarOpen: false }" class="flex h-screen bg-gray-200">
        <div :class="sidebarOpen ? 'block' : 'hidden'" @click="sidebarOpen = false" class="fixed z-20 inset-0 bg-black opacity-50 transition-opacity lg:hidden"></div>
        <!-- Sidebar -->
        <%= render "dashboard/shared/sidebar" %>
          
        <div class="flex-1 flex flex-col overflow-hidden">
        <!-- Header -->
        <%= render "dashboard/shared/header" %>
            <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
                <div class="container mx-auto px-6 py-8">
                    <h3 class="text-gray-700 text-2xl font-medium">Config Lnclass</h3>
                    <div class="mt-8">
                        <!-- Header -->
                        <%= render "dashboard/shared/statistics" %>
                    </div>
    
                    <div class="flex flex-col mt-8">
                    <h3 class="text-gray-700 text-2xl font-medium">Nouveaux Membres</h3>
                        <%= render "dashboard/shared/members-list" %>
                    </div>
                </div>
            </main>
        </div>
    </div>
</div>

app/views/dashboard/shared/_header.html.erb
<header class="flex justify-between items-center py-4 px-6 bg-white border-b-4 border-indigo-600">
    <div class="flex items-center">
        <button @click="sidebarOpen = true" class="text-gray-500 focus:outline-none lg:hidden">
            <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M4 6H20M4 12H20M4 18H11" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                    stroke-linejoin="round"></path>
            </svg>
        </button>
    
        <div class="relative mx-4 lg:mx-0">
            <span class="absolute inset-y-0 left-0 pl-3 flex items-center">
                <svg class="h-5 w-5 text-gray-500" viewBox="0 0 24 24" fill="none">
                    <path
                        d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    </path>
                </svg>
            </span>
    
            <input class="form-input w-32 sm:w-64 rounded-md pl-10 pr-4 focus:border-indigo-600" type="text"
                placeholder="Recherche">
        </div>
    </div>
    
    <div class="flex items-center">
        <div x-data="{ notificationOpen: false }" class="relative">
            <button @click="notificationOpen = ! notificationOpen"
                class="flex mx-4 text-gray-600 focus:outline-none">
                <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M15 17H20L18.5951 15.5951C18.2141 15.2141 18 14.6973 18 14.1585V11C18 8.38757 16.3304 6.16509 14 5.34142V5C14 3.89543 13.1046 3 12 3C10.8954 3 10 3.89543 10 5V5.34142C7.66962 6.16509 6 8.38757 6 11V14.1585C6 14.6973 5.78595 15.2141 5.40493 15.5951L4 17H9M15 17V18C15 19.6569 13.6569 21 12 21C10.3431 21 9 19.6569 9 18V17M15 17H9"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    </path>
                </svg>
            </button>
    
            <div x-show="notificationOpen" @click="notificationOpen = false"
                class="fixed inset-0 h-full w-full z-10" style="display: none;"></div>
    
            <div x-show="notificationOpen"
                class="absolute right-0 mt-2 w-80 bg-white rounded-lg shadow-xl overflow-hidden z-10"
                style="width: 20rem; display: none;">
                <a href="#"
                    class="flex items-center px-4 py-3 text-gray-600 hover:text-white hover:bg-indigo-600 -mx-2">
                    <img class="h-8 w-8 rounded-full object-cover mx-1"
                        src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=334&amp;q=80"
                        alt="avatar">
                    <p class="text-sm mx-2">
                        <span class="font-bold" href="#">Sara Salah</span> vient d'adherer <span
                            class="font-bold text-indigo-400" href="#">Nouveau membre</span>. 2m
                    </p>
                </a>
                <a href="#"
                    class="flex items-center px-4 py-3 text-gray-600 hover:text-white hover:bg-indigo-600 -mx-2">
                    <img class="h-8 w-8 rounded-full object-cover mx-1"
                        src="https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=634&amp;q=80"
                        alt="avatar">
                    <p class="text-sm mx-2">
                        <span class="font-bold" href="#">Slick Action+</span> a fait un don. 45m
                    </p>
                </a>
                <a href="#"
                    class="flex items-center px-4 py-3 text-gray-600 hover:text-white hover:bg-indigo-600 -mx-2">
                    <img class="h-8 w-8 rounded-full object-cover mx-1"
                        src="https://images.unsplash.com/photo-1450297350677-623de575f31c?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=334&amp;q=80"
                        alt="avatar">
                    <p class="text-sm mx-2">
                        <span class="font-bold" href="#">Koné Ngolo</span> a telecharger  <span
                            class="font-bold text-indigo-400" href="#"> le formulaire de don</span>. 1h
                    </p>
                </a>
                <a href="#"
                    class="flex items-center px-4 py-3 text-gray-600 hover:text-white hover:bg-indigo-600 -mx-2">
                    <img class="h-8 w-8 rounded-full object-cover mx-1"
                        src="https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=398&amp;q=80"
                        alt="avatar">
                    <p class="text-sm mx-2">
                        <span class="font-bold" href="#">Kamaté</span> a fait un don . 3h
                    </p>
                </a>
            </div>
        </div>
    
        <div x-data="{ dropdownOpen: false }" class="relative">
            <button @click="dropdownOpen = ! dropdownOpen"
                class="relative block h-8 w-8 rounded-full overflow-hidden shadow focus:outline-none">
                <img class="h-full w-full object-cover"
                    src="https://images.unsplash.com/photo-1528892952291-009c663ce843?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=296&amp;q=80"
                    alt="Your avatar">
            </button>
    
            <div x-show="dropdownOpen" @click="dropdownOpen = false" class="fixed inset-0 h-full w-full z-10"
                style="display: none;"></div>
    
            <div x-show="dropdownOpen"
                class="absolute right-0 mt-2 w-48 bg-white rounded-md overflow-hidden shadow-xl z-10"
                style="display: none;">
                <a href="#"
                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-indigo-600 hover:text-white">Profile</a>
                <a href="#"
                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-indigo-600 hover:text-white">Parametres</a>
                <a href="#"
                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-indigo-600 hover:text-white">Déconnecter</a>
            </div>
        </div>
    </div>
</header>

app/views/dashboard/shared/_sidebar.html.erb
<div :class="sidebarOpen ? 'translate-x-0 ease-out' : '-translate-x-full ease-in'" class="fixed z-30 inset-y-0 left-0 w-64 transition duration-300 transform bg-gray-900 overflow-y-auto lg:translate-x-0 lg:static lg:inset-0">
    <div class="flex items-center justify-center mt-8">
        <div class="flex items-center">       
            <span class="text-white text-2xl mx-2 font-semibold">Lnclass Admin</span>
        </div>
    </div>
    
    <nav class="mt-10">
        <%= link_to root_path, class:"flex items-center mt-4 py-2 px-6 bg-gray-700 bg-opacity-25 text-gray-100" do %>
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z"></path>
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z"></path>
            </svg>
    
            <span class="mx-3">Dashboard</span>
        <% end %>
    
        <%= link_to "courses-show", class:"flex items-center mt-4 py-2 px-6 text-gray-500 hover:bg-gray-700 hover:bg-opacity-25 hover:text-gray-100" do %>
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M17 14v6m-3-3h6M6 10h2a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v2a2 2 0 002 2zm10 0h2a2 2 0 002-2V6a2 2 0 00-2-2h-2a2 2 0 00-2 2v2a2 2 0 002 2zM6 20h2a2 2 0 002-2v-2a2 2 0 00-2-2H6a2 2 0 00-2 2v2a2 2 0 002 2z">
                </path>
            </svg>
            <span class="mx-3">Léçons</span>
        <% end %>
    
        <%= link_to 'lesson', class:"flex items-center mt-4 py-2 px-6 text-gray-500 hover:bg-gray-700 hover:bg-opacity-25 hover:text-gray-100" do %>
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10">
                </path>
            </svg>
    
            <span class="mx-3">Nouvelle Léçon</span>
        <% end %>
    
        <%= link_to "/analytics", class:"flex items-center mt-4 py-2 px-6 text-gray-500 hover:bg-gray-700 hover:bg-opacity-25 hover:text-gray-100" do %>
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z">
                </path>
            </svg>
            <span class="mx-3">Analytics</span>
        <% end %>
        <%= link_to setting_path, class:"flex items-center mt-4 py-2 px-6 text-gray-500 hover:bg-gray-700 hover:bg-opacity-25 hover:text-gray-100" do %>
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z">
                </path>
            </svg>
            <span class="mx-3">Parametres</span>
        <% end %>
                
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete } , class:"flex items-center mt-4 py-2 px-6 text-gray-500 hover:bg-gray-700 hover:bg-opacity-25 hover:text-gray-100" do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
            <span class="mx-3">Déconnecter</span>
        <% end %>
    </nav>
</div>