config/routes.rb
Rails.application.routes.draw do
  
  resources :flash_cards
  resources :user_echanges, except: [:create, :new]
  resources :flashes, except: [:create, :index, :new]
  
  
  #Course items
  resources :courses, shallow: true do
    resources :flashes, only: [:create, :index, :new]
    resources :user_echanges, only: [:create, :new]
  end
  #resources :flash_cards, except:[:index, :show] do
    # resources :line_items, except: [:index, :show]
  #end
  
  #Membership
  get "teacher-sign-up" , to:'membership#teacherUp'
  get "teacher-sign-in" , to:'membership#teacherIn'
  get "ambassadeur-sign-up" , to:'membership#ambassadorUp'
  get "ambassadeur-sign-in" , to:'membership#ambassadorIn'
  get "team-sign-up" , to:'membership#teamUp'
  get "team-sign-in" , to:'membership#teamIn'

   #Home && Feed
  get "home", to:'home#index'

  #Courses
  get "courses-show", to:"courses#show"
  get "feed", to:"courses#index"
  get "lesson", to:"courses#new"
  
  #Dashboard
  get "dashboard", to:'dashboard#index'
  get "setting", to:'dashboard#home'
  get "new-materials", to:"materials#new"
  get "new-levels", to:"levels#new"
  get "new-city", to:"citytowns#new"
  get "new-school", to:"schools#new"

  
  resources :courses
  resources :user_roles
  resources :schools
  resources :citytowns
  resources :materials
  resources :levels
  
  #Membership 
  devise_scope :user do
    get '/student-sign-in', to: 'devise/sessions#new'
    get '/student-sign-up', to: 'devise/registrations#new', as: "new_user_registration"
    delete '/sign-out', to: 'devise/sessions#destroy'
  end

  devise_for :users
  root to:'homepage#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/citytown.rb
class Citytown < ApplicationRecord
  belongs_to :user

  #Slugged concern
  include ItemsSlugged

end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  has_many :flashes, dependent: :destroy
  has_many :flash_cards, dependent: :destroy
  has_many :user_echanges, class_name: "UserEchange",
                            foreign_key: "course_id",
                            dependent: :destroy

  ################## FIX N+1  ###############
Course.all.with_rich_text_content # Preload the body without attachments.
Course.all.with_rich_text_content_and_embeds # Preload both body and attachments.


##### STATUS  ########
STATUS = ["Lune", "Old"]

  ################## SLUG ###############
  validates :title, :content, :published,
            :level_name, :material_name,
            :user_id, :slug, :status, presence: true

  def slugged_custom
    #Apprendre-a-calculer-les-limites-math-tleD
    "#{title} #{material_name} #{level_name}"
  end

  extend FriendlyId
    friendly_id :slugged_custom, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end

  #Scopeto find essential for course
  scope :essential, -> { where("feed_course.id = ?", feed_flash.course_id)}
  # Ex:- scope :active, -> {where(:active => true)}
end

app/models/flash.rb
class Flash < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_rich_text :content
  
  #setup validation and uniqueness
  validates :title, presence: true, uniqueness: { scope: :course_id }
  validates :content, :slug, :user_id, :course_id, presence: true

  #Slugged concern
  include ItemsSlugged


end

app/models/flash_card.rb
class FlashCard < ApplicationRecord
  belongs_to :course
  belongs_to :user

  
  #setup validation and uniqueness
  validates :slug, :user_id, :course_id, presence: true
  validates :title, presence: true, uniqueness: { scope: :course_id }
  
  #Slugged concern
  include ItemsSlugged


end

app/models/home.rb
class Home < ApplicationRecord


end   

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :user

  #Slugged concern
  include ItemsSlugged
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :user

  #Slugged concern
  include ItemsSlugged

  
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :user

  #Slugged concern
  include ItemsSlugged

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :trackable,  :authentication_keys => [:logged]

has_many :levels, class_name: "Level", foreign_key: "user_id"
has_many :materials, class_name: "Material", foreign_key: "user_id"
has_many :schools, class_name: "School", foreign_key: "user_id"
has_many :citytowns, class_name: "Citytown", foreign_key: "user_id"
has_many :courses, class_name: "Course", foreign_key: "user_id"
has_many :flashes
has_many :flash_cards
has_many :user_echanges, class_name: "User_echange", foreign_key: "user_id"


            
attr_writer :logged
  #enum :role, student: "student", teacher: "teacher", team: "team", default: "student"
  
  
  ################## VALIDATES  ###############
  before_validation :user_validations?,  on: :create
  before_validation :full_name
   
  
   validates :first_name, :last_name, :full_name, :email, :password,
              :contact, :user_role, :city_name, presence: true

   validates :contact, uniqueness: true, numericality: { only_integer: true }, length: { minimum:10,
              message: "%{ value} verifier votre nom numéro est 10 chiffres"}
              
   validates :user_role, inclusion: { in: %w(Student Teacher Team ambassador),
                    message: "%{value} acces non identifier" }


   ############# CUSTOMIZE ###############""
   
   def user_validations?
    if self.user_role != "Student"
      self.matricule = "#{self.contact}T"
    else 
      self.email = "#{self.matricule}@gmail.com"
      self.password = "#{self.contact}"
    end    
  end

  #FULL_NAME
  def full_name
    self.full_name = "#{self.first_name} #{self.last_name}" 
  end 

################## SLUG ###############
  extend FriendlyId
  friendly_id :user_slugged, use: :slugged
  
  def user_slugged
    [
      :full_name,
    [:full_name, :contact]
    ]
  end
  ################## END SLUGGED #########

  ################## BEFORE SAVE  #########
  before_save do
    self.contact            = contact.strip.squeeze(" ")
    self.first_name         = first_name.strip.squeeze(" ").downcase.capitalize
    self.last_name          = last_name.strip.squeeze(" ").downcase.capitalize
  end
    
  ################## LOGGED  #########
  #permet la connexion avec le matricule
  def logged
    @logged || self.matricule || self.email
  end
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (logged = conditions.delete(:logged))
      where(conditions.to_h).where(["lower(matricule) = :value OR lower(email) = :value", { :value => logged.downcase }]).first
    elsif conditions.has_key?(:matricule) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
  
  ################## End Logged  #########
end

app/models/user_echange.rb
class UserEchange < ApplicationRecord
  belongs_to :course
  belongs_to :user
  has_rich_text :content
  has_rich_text :wiki


 ################## FIX N+1  ###############
Course.all.with_rich_text_content # Preload the body without attachments.
Course.all.with_rich_text_content_and_embeds # Preload both body and attachments.


##### STATUS  ########
STATUS = ["Lune", "Old"]

  ################## SLUG ###############
  validates :title, :course_id, :user_id, :slug, presence: true

  def slugged_custom
    #Apprendre-a-calculer-les-limites-math-tleD
    "#{title} #{course_id}"
  end

  extend FriendlyId
    friendly_id :slugged_custom, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end

end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
end

app/controllers/membership_controller.rb
class MembershipController < ApplicationController
  def teacherUp
  end

  def teacherIn
  end

  def ambassadorUp
  end

  def ambassadorIn
  end

  def teamUp
  end

  def teamIn
  end
end

app/helpers/citytowns_helper.rb
module CitytownsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/membership_helper.rb
module MembershipHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/membership/ambassadorIn.html.erb
<% @title="Se connecter Ambassadeurs" %>

  <div class="container-fluid" >
    <div class="flex flex-wrap ">
      <div class="m-auto border border-x-slate-300 ">
        <!-- Header -->
        <%= render "membership/shared/header" %>

        <div class="px-4 md:px-32 py-8">
          <h2 class="flex justify-center text-2xl text-white font-bold">Connexion des Ambassadeurs</h2>      
        <!-- forms -->
        <%= render "membership/shared/sign_in" %>
        </div>
      </div>
    </div> 
  </div>

app/views/membership/ambassadorUp.html.erb
<% @title="S'Inscription Ambassador" %>
<div class="container-fluid" >
	<div class="flex flex-wrap ">
		<div class="m-auto border border-x-slate-300 ">
			<div class="my-2 flex justify-center">
	<h1 class="text-white font-bold font-bold text-4xl">
		<span class="">Ln<span class="ln-logo-decor">class</span></span>
	</h1>
</div>
<div class="flex border-y border-y-slate-300 py-2 px-4 md:-px-32 text-white  justify-center">
	<div class="">
		
		<span class=" ml-4"><%= link_to 'Ambassadeur', "/ambassadeur-sign-up" %></span>
	</div>
</div>
			<div class="px-4 md:px-302 py-8">
				<h2 class="flex justify-center text-2xl text-white font-bold">Incription Ambassadeur</h2>
				<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
				<%= render "devise/shared/error_messages", resource: resource %>
				<!-- Error-->
				<%#= form_error_notification(resource: resource) %>
				<div class="py-8 pb-2">			
					<div class="py-8 pb-2">
						<div class="py-8 max-w-md">
							<div class="grid grid-cols-1 gap-6">
								<label class="block"><span class="text-white">Nom: </span><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", placeholder:"Ex: Konan Yao ...",class:"mt-1 ln-field" %></label>
							</div>
						</div>
						<div class="py-8 max-w-md">
							<div class="grid grid-cols-1 gap-6">
								<label class="block"><span class="text-white">Prénom: </span><%= f.text_field :last_name,  placeholder:"Ex: Angela ...", class:"mt-1 ln-field" %></label>
							</div>
						</div>
						
											
						<div class="py-8 max-w-md">
							<div class="grid grid-cols-1 gap-2">
								<span class="text-white ">N° whatsapp ou N° joingnable par appel</span>
								<%= f.phone_field :contact, placeholder:"Ex: 0584258085", class:"ln-field" %>
							</div>
						</div>
						<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-2">
							<span class="text-white ">Nom de votre media</span>
							<%= f.text_field :media_name, placeholder:"Ex: Facebook groupe prépa Philo", class:"ln-field" %>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-2">
							<span class="text-white">Ville:</span>
							<%= f.select(:city_name, @citytowns.map{|citytown| [citytown.title]}, { prompt: "Choisir" }, class:"ln-select") %>
					
						</div>
					</div>
						<div class="py-8 max-w-md">
							<div class="grid grid-cols-1 gap-2">
								<span class="text-white ">Adresse Email:</span>
								<%= f.email_field :email, placeholder:"Ex: Lnclass@gmail", class:"ln-field" %>
							</div>
						</div>
						<div class="py-8 max-w-md">
							<div class="grid grid-cols-1 gap-2">
								<span class="text-white ">Mot de passe:</span>
								<%= f.password_field :password, placeholder:"Ex: ********", class:"ln-field" %>
							</div>
						</div>
						<div class="py-8 max-w-md">
							<div class="grid grid-cols-1 gap-6 pt-4">
								<div class="block">
									<%= f.label :"Je suis :" , class:"text-white" %>
									<br>
									<%= f.radio_button :gender, "Femme", id:"fenale", class:"bg-white font-bold" , checked: true %>
									<label for="fenale" class="text-bold text-white">Une Femme</label>
									<%= f.radio_button :gender, "Homme",id:"male", class:"bg-white font-bold pl-4" %>
									<label for="male" class="text-bold text-white">Un Homme</span>
								</div>
							</div>
						</div>
						<div class="py-8 max-w-md">
							<div class="grid grid-cols-1 gap-6">
								<div class="py-8 max-w-md">
									<div class="grid grid-cols-1 gap-6">
											<p class="text-white">
												Vérifiez que vous avez bien remplir les champs avec les bonnes informations avant de clicker sur Inscription. 
											</p>
										
									</div>
								</div>
							</div>
						</div>
					
							<%= f.hidden_field :user_role, value:"Ambassador" %>
							<div class="pt-4 mt-6">
								<%= f.submit "Inscription Ambassadeur", class:"ln-button" %>
							</div>
						<% end %>
				</div>
			</div>
		</div>
	</div>

app/views/membership/shared/_sign_in.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
	<!-- Error-->
	<%#= form_error_notification(resource: resource) %>
	<!-- This is an example component -->
	<div  class='flex items-center justify-center'>
		<div class='w-full max-w-lg px-10 py-8 mx-auto bg-white rounded-lg shadow-xl'>
			<!-- matricule -->
			<div class='max-w-md mx-auto  space-y-6'>
				<div class="space-y-2 text-gray-700">
					<label class="block font-medium text-smmx-auto " >Email:</label>
					<div class="relative  focus-within:text-gray-900 ">
						<%= f.email_field :email, autofocus:true, autocomplete:"email",  placeholder:"Ex: Lnclass@gmail.com",class:"pl-11 text-gray-800 pr-11 py-2 border-gray-600 rounded-md focus:border-gray-400focus:ringfocus:ring-gray-800 ring-gray-400 ring focus:ring-offset-2 focus:ring-offset-whiteblock w-full" %>
					</div>
				</div>
			</div>
			<!-- password-->
                  <div class='max-w-md mx-auto  space-y-6'>
                    <div  x-show="">
                      <div class="space-y-2 text-gray-700" x-data="{}">
                        <label class="block font-medium text-smmx-auto " for="password">Mot de passe</label>
                        <div class="relative  focus-within:text-gray-900 ">
                          <div aria-hidden="true" class="absolute inset-y-0 flex items-center px-4 pointer-events-none">
                            <svg aria-hidden="true" class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path>
                            </svg>
                          </div>
                          <input placeholder="Ex: xxxx xx xxx" 
                          class="pl-11 text-gray-800 pr-11 py-2 border-gray-600 rounded-md focus:border-gray-400
                          focus:ringfocus:ring-gray-800 ring-gray-400 ring focus:ring-offset-2 
                          focus:ring-offset-white block w-full" 
                          id="password"
                            autocomplete="new-password" 
                            type="password" name="user[password]" 
                            x-bind:type="isshow ? 'text' : 'password'" />
                          <div class="absolute right-0 z-30 inset-y-1 flex items-center px-4 ">
                            <button type="button" @click="isshow=!isshow" class="z-30 ">
                              <svg x-show="!isshow" aria-hidden="true" class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
                              </svg>
                              <svg x-show="isshow" aria-hidden="true" class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" style="display: none;">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"></path>
                              </svg>
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>



			<div class="my-2">
				<% if devise_mapping.rememberable? %>
				<%= f.check_box :remember_me %>
				<%= f.label :"Restez connecter à mon compte" %>
				<% end %>
			</div>
			<div class="mt-4 max-w-md">
				<div class="grid grid-cols-1 gap-6">
					<label class="block my-4"><p class="text-black">Cette page est protégée par Google reCAPTCHA pour nous assurer que vous n'êtes pas un robot. </p></label>
				</div>
			</div>
			<div class="mt-10 ">
				<%= f.submit "Connexion", class:"bg-blue-500 text-white font-bold p-3 px-6 rounded-full mt-2" %>
			</div>
			<% end %>

app/views/membership/teacherIn.html.erb
<% @title="Se connecter prof" %>

  <div class="container-fluid" >
    <div class="flex flex-wrap ">
      <div class="m-auto border border-x-slate-300 ">
        <!-- Header -->
        <%= render "membership/shared/header" %>

        <div class="px-4 md:px-32 py-8">
          <h2 class="flex justify-center text-2xl text-white font-bold">Connexion des Profs</h2>      
        <!-- forms -->
        <%= render "membership/shared/sign_in" %>
        </div>
      </div>
    </div> 
  </div>

app/views/membership/teacherUp.html.erb
<% @title="S'Inscription Profs" %>
<div class="container-fluid" >
	<div class="flex flex-wrap ">
		<div class="m-auto border border-x-slate-300 ">
			<%= render "membership/shared/sign_up/header" %>
			<div class="px-4 md:px-302 py-8">
				<h2 class="flex justify-center text-2xl text-white font-bold">Incription </h2>
				<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
				<%= render "devise/shared/error_messages", resource: resource %>
				<!-- Error-->
				<%#= form_error_notification(resource: resource) %>
				<div class="py-8 pb-2">
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-6">
							<label class="block"><span class="text-white">Nom: </span><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", placeholder:"Ex: Konan Yao ...",class:"mt-1 block w-full" %></label>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-6">
							<label class="block"><span class="text-white">Prénom: </span><%= f.text_field :last_name,  placeholder:"Ex: Angela ...", class:"mt-1 block w-full" %></label>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-2">
							<span class="text-white">Ville:</span>
							<%= f.select(:city_name, @citytowns.map{|citytown| [citytown.title]}, { prompt: "Choisir" }, class:"ln-select") %>
						</div>
					</div>
					<div class="py-12 max-w-md">
						<div class="grid grid-cols-1 gap-2">
							<span class="text-white ">Nom établissement: </span>
							<%= f.text_field :school_name, placeholder:"Ex: College Moderne Saint Michel Tiassalé", class:"mt-1 block w-full" %>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-2">
							<span class="text-white">Discipline Enseignée:</span>
							<%= f.select(:material_name, @materials.map{|material| [material.title]}, { prompt: "Choisir" }, class:"ln-select") %>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-2">
							<span class="text-white ">N° whatsapp ou N° joingnable par appel</span>
							<%= f.phone_field :contact, placeholder:"Ex: 0584258085", class:"block w-full" %>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-2">
							<span class="text-white ">Adresse Email:</span>
							<%= f.email_field :email, placeholder:"Ex: Lnclass@gmail", class:"block w-full" %>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-2">
							<span class="text-white ">Mot de passe:</span>
							<%= f.password_field :password, placeholder:"Ex: ********", class:"block w-full" %>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-6 pt-4">
							<div class="block">
								<%= f.label :"Je suis :" , class:"text-white" %>
								<br>
								<%= f.radio_button :gender, "Femme", id:"fenale", class:"bg-white font-bold" , checked: true %>
								<label for="fenale" class="text-bold text-white">Une Femme</label>
								<%= f.radio_button :gender, "Homme",id:"male", class:"bg-white font-bold pl-4" %>
								<label for="male" class="text-bold text-white">Un Homme</span>
							</div>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-6 py-4">
							<div class="block">
								<%= f.label :"Important: Savez-vous utilier un Ordinateur ?" , class:"font-bold underline text-white" %>
								<br>
								<%= f.radio_button :doublant, "Non", id:"non", class:"bg-white font-bold", checked: true %>
								<label for="non" class="text-bold text-white">Non</label>
								<%= f.radio_button :doublant, "Non",id:"non", class:"bg-white font-bold pl-4" %>
								<label for="Oui" class="text-bold text-white">Oui</span>
								<divl></div>
							</div>
							<div class="py-8 max-w-md">
								<div class="grid grid-cols-1 gap-6">
									<div class="block my-4">
										<p class="text-white">
											Vérifiez que vous avez bien remplir les champs avec les bonnes informations avant de clicker sur Inscription. 
										</p>
									</div>
								</div>
							</div>
							<%= f.hidden_field :user_role, value:"Teacher" %>
							<div class="pt-4 my-6">
								<%= f.submit "Inscription Professeur", class:"ln-button" %>
							</div>
						</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/membership/teamIn.html.erb
<% @title="Se connecter Teams" %>

  <div class="container-fluid" >
    <div class="flex flex-wrap ">
      <div class="m-auto border border-x-slate-300 ">
        <!-- Header -->
        <%= render "membership/shared/header" %>

        <div class="px-4 md:px-32 py-8">
          <h2 class="flex justify-center text-2xl text-white font-bold">Connexion Teams</h2>      
        <!-- forms -->
        <%= render "membership/shared/sign_in" %>
        </div>
      </div>
    </div> 
  </div>

app/views/membership/teamUp.html.erb
<% @title="S'Inscription Team" %>
<div class="container-fluid" >
	<div class="flex flex-wrap ">
		<div class="m-auto border border-x-slate-300 ">
			<div class="my-2 flex justify-center">
	<h1 class="text-white font-bold font-bold text-4xl">
		<span class="">Ln<span class="ln-logo-decor">class</span></span>
	</h1>
</div>
<div class="flex border-y border-y-slate-300 py-2 px-4 md:-px-32 text-white  justify-center">
	<div class="">
		<span class=""><%= link_to 'Student', "/student-sign-up" %></span>
		<span class=" ml-4"><%= link_to 'Teacher', "/teacher-sign-up" %></span>
		<span class=" ml-4"><%= link_to 'Ambassadeur', "/ambassadeur-sign-up" %></span>
	</div>
</div>
			<div class="px-4 md:px-302 py-8">
				<h2 class="flex justify-center text-2xl text-white font-bold">Incription Team</h2>
				<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
				<%= render "devise/shared/error_messages", resource: resource %>
				<!-- Error-->
				<%#= form_error_notification(resource: resource) %>
				<div class="py-8 pb-2">
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-6">
							<label class="block"><span class="text-white">Nom: </span><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", placeholder:"Ex: Konan Yao ...",class:"mt-1 ln-field" %></label>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-6">
							<label class="block"><span class="text-white">Prénom: </span><%= f.text_field :last_name,  placeholder:"Ex: Angela ...", class:"mt-1 ln-field" %></label>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-6">
							<label class="block"><span class="text-white">Ville: </span>
             				 <%= f.text_field :city_name,  placeholder:"Ex: Tiassalé ...", class:"ln-field" %></label>
						</div>
					</div>
										
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-2">
							<span class="text-white ">N° whatsapp ou N° joingnable par appel</span>
							<%= f.phone_field :contact, placeholder:"Ex: 0584258085", class:"ln-field" %>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-2">
							<span class="text-white ">Adresse Email:</span>
							<%= f.email_field :email, placeholder:"Ex: Lnclass@gmail", class:"ln-field" %>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-2">
							<span class="text-white ">Mot de passe:</span>
							<%= f.password_field :password, placeholder:"Ex: ********", class:"ln-field" %>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-6 pt-4">
							<div class="block">
								<%= f.label :"Je suis :" , class:"text-white" %>
								<br>
								<%= f.radio_button :gender, "Femme", id:"fenale", class:"bg-white font-bold" , checked: true %>
								<label for="fenale" class="text-bold text-white">Une Femme</label>
								<%= f.radio_button :gender, "Homme",id:"male", class:"bg-white font-bold pl-4" %>
								<label for="male" class="text-bold text-white">Un Homme</span>
							</div>
						</div>
					</div>
					<div class="py-8 max-w-md">
						<div class="grid grid-cols-1 gap-6">
							<div class="py-8 max-w-md">
								<div class="grid grid-cols-1 gap-6">
										<p class="text-white">
											Vérifiez que vous avez bien remplir les champs avec les bonnes informations avant de clicker sur Inscription. 
										</p>
									
								</div>
							</div>
						</div>
					</div>
							<%= f.hidden_field :user_role, value:"Team" %>
							<div class="pt-4 mt-6">
								<%= f.submit "Inscription Team", class:"ln-button" %>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>